import { useEffect, useState } from "react";

const names = [
  "Henry M.",
  "Melissa G.",
  "Vince P.",
  "Ava R.",
  "Liam N.",
  "Sophia T.",
  "Noah W.",
  "Isabella Z.",
  "Mason J.",
  "Emma K.",
  "James H.",
  "Olivia F.",
  "Lucas C.",
  "Amelia B.",
  "Ethan D.",
  "Charlotte A.",
  "Logan Q.",
  "Harper E.",
  "Aiden Y.",
  "Mia S.",
  "Benjamin L.",
  "Abigail N.",
  "Elijah V.",
  "Emily R.",
  "Daniel K.",
  "Chloe H.",
  "Matthew P.",
  "Ella G.",
  "Sebastian F.",
  "Lily J.",
  "Jack T.",
  "Aria W.",
  "Owen D.",
  "Scarlett M.",
  "Samuel B.",
  "Grace V.",
  "Jacob E.",
  "Zoe Q.",
  "Michael S.",
  "Nora A.",
  "Alexander L.",
  "Layla Z.",
  "Carter Y.",
  "Riley U.",
  "Wyatt O.",
  "Lillian I.",
  "Jayden N.",
  "Hannah C.",
  "Gabriel X.",
  "Aubrey W.",
  "Julian R.",
  "Addison T.",
  "Levi H.",
  "Ellie B.",
  "David M.",
  "Savannah L.",
  "Isaac P.",
  "Brooklyn G.",
  "Anthony K.",
  "Audrey F.",
  "Joseph J.",
  "Bella E.",
  "John D.",
  "Claire Z.",
  "Luke N.",
  "Lucy S.",
  "Dylan C.",
  "Camila M.",
  "Andrew Y.",
  "Skylar O.",
  "Christopher W.",
  "Paisley A.",
  "Grayson L.",
  "Anna T.",
  "Joshua Q.",
  "Hailey K.",
  "Nathan R.",
  "Stella V.",
  "Thomas G.",
  "Penelope F.",
  "Caleb X.",
  "Aaliyah B.",
  "Eli M.",
  "Violet E.",
  "Isaiah S.",
  "Naomi J.",
  "Hunter D.",
  "Caroline H.",
  "Lincoln P.",
  "Genesis T.",
  "Hudson C.",
  "Eva L.",
  "Christian W.",
  "Serenity Y.",
  "Jonathan A.",
  "Kennedy N.",
  "Aaron Z.",
  "Sadie V.",
  "Charles Q.",
  "Madelyn M.",
  "Connor F.",
  "Peyton B.",
  "Jeremiah K.",
  "Alexa G.",
];

const locations = [
  "Denmark",
  "United States",
  "Poland",
  "Germany",
  "Australia",
  "Canada",
  "Brazil",
  "Japan",
  "Mexico",
  "Netherlands",
  "Sweden",
  "Norway",
  "Switzerland",
  "Finland",
  "France",
  "Italy",
  "Spain",
  "Austria",
  "Belgium",
  "Ireland",
  "United Kingdom",
  "New Zealand",
  "Portugal",
  "South Korea",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Vietnam",
  "Philippines",
  "India",
  "Pakistan",
  "Bangladesh",
  "Nepal",
  "Sri Lanka",
  "China",
  "Hong Kong",
  "Taiwan",
  "Russia",
  "Ukraine",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Slovakia",
  "Slovenia",
  "Croatia",
  "Serbia",
  "Greece",
  "Turkey",
  "Israel",
  "Saudi Arabia",
  "United Arab Emirates",
  "Qatar",
  "Kuwait",
  "Egypt",
  "South Africa",
  "Kenya",
  "Nigeria",
  "Morocco",
  "Algeria",
  "Tunisia",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "Ecuador",
  "Uruguay",
  "Paraguay",
  "Bolivia",
  "Panama",
  "Costa Rica",
  "Guatemala",
  "Honduras",
  "El Salvador",
  "Cuba",
  "Jamaica",
  "Trinidad and Tobago",
  "Bahamas",
  "Iceland",
  "Luxembourg",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Georgia",
  "Armenia",
  "Azerbaijan",
  "Kazakhstan",
  "Uzbekistan",
  "Iran",
  "Iraq",
  "Syria",
  "Jordan",
  "Lebanon",
  "Oman",
  "Yemen",
  "Afghanistan",
  "Ethiopia",
  "Ghana",
  "Zimbabwe",
  "Zambia",
  "Botswana",
];

const membershipTypes = [
  "Basic Membership 🏁🔥",
  "Plus+ Membership 🚀🌟",
  "VIP Membership 😈📈",
];

const getRandomItem = <T,>(arr: T[]): T =>
  arr[Math.floor(Math.random() * arr.length)];

export default function ToastPopup() {
  const [show, setShow] = useState(false);
  const [message, setMessage] = useState("");

  useEffect(() => {
    const showToast = () => {
      const name = getRandomItem(names);
      const location = getRandomItem(locations);
      const membership = getRandomItem(membershipTypes);
      const msg = `${name} from ${location} has just purchased T-Stackz Rackz ${membership}`;
      setMessage(msg);
      setShow(true);
      setTimeout(() => setShow(false), 4000);
    };

    showToast();
    const interval = setInterval(showToast, 15000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div
      className={`fixed top-5 left-5 z-50 transition-all duration-500 ease-in-out ${
        show ? "translate-x-0 opacity-100" : "-translate-x-full opacity-0"
      } bg-[#D72638] text-white px-4 py-3 rounded-lg shadow-lg w-[300px] flex items-center gap-3`}
    >
      <span>{message}</span>
    </div>
  );
}
